### PR TITLE
Feature/client activities

### LINKED ISSUE #3: Client scaffold
- [x] Init a react app in the client scaffold
- [x] Add blockly
- [x] Serial api
- [x] Integrate with backend via REST calls to access activity list. 
- [x] Integrate with backend via REST calls to customize workspace. 
- [x] Finalize Client documentation BEFORE making a PR
- [x] Setup frontend middleware to properly serve react + routing
- [x] Configure build to handle new serving

### PR DESCRIPTION
**Pull request by rennemannd**
- Sets up multi page routing
- Adds dynamic block rendering based on activity
- Cleaned up warning messages
- Cleaned up documentation

Closes #3

### CODE REVIEW

**Comment by nionata** [comment]
https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually

good explanation of the routing issues. strapi looks for directories and their respective index.html when public requests are made. so /home will not get the base index.html and will instead look for public/home/index.html, which will 404...we maybe have to redirect this route

**Comment by nionata** [comment]
The routing issue will be temporarily handled w/ a custom middleware. This will allow us to still serve static content along side our frontend. Eventually, we will migrate to a separate web server for the frontend.

**Comment by rennemannd** [comment]
@nionata review when you can, should work as intended now when built

**Comment by nionata** [comment]
Screen Shot 2020-05-31 at 9 35 17 AM

On `yarn start` – it can probably be solved by moving the const down below all the imports

**Comment by nionata** [comment]
@rennemannd the build compile issue seems to be resolve!

**Comment by rennemannd** [comment]
Ouch my bad on that, I got wrapped up in fixing the compilation error on build and ended up stashing the other fixes and forgetting about them. Just pushed them @nionata with the path for the workspace just being /workspace now.

**Pull request merged**
